name: Manual Version Bump

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Target version (e.g., 500.0.0)'
        required: true
        type: string

permissions:
  contents: write
  actions: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Create and push version tag
        run: |
          git tag -a "v$((${{ inputs.version }} - 1))" -m "Version $((${{ inputs.version }} - 1))"
          git push origin "v$((${{ inputs.version }} - 1))"

      - name: Create empty commit for version bump
        run: |
          git commit --allow-empty -m "fix!: bumping major version ${{ inputs.version }}"
          git push origin main

      - name: Trigger prod release workflow
        run: |
          gh workflow run "Prod Publish" --ref main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Wait for release workflow
      #   run: |
      #     echo "Waiting for prod release workflow to complete..."
      #     sleep 30  # Give time for the workflow to start
      #     gh run watch $(gh run list --workflow="Prod Publish" --branch main --json databaseId --jq '.[0].databaseId')
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 